# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stats.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstats.proto\x12\rstats_service\"H\n\x17PostStatsByOneParameter\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nuser_login\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\"!\n\x13GetPostStatsRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"4\n\x14GetPostStatsResponse\x12\r\n\x05likes\x18\x01 \x01(\x05\x12\r\n\x05views\x18\x02 \x01(\x05\";\n\x16GetPopularPostsRequest\x12\x13\n\x0b\x61\x63tion_type\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x05\"P\n\x17GetPopularPostsResponse\x12\x35\n\x05posts\x18\x01 \x03(\x0b\x32&.stats_service.PostStatsByOneParameter\"\'\n\x16GetPopularUsersRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"(\n\x08UserInfo\x12\r\n\x05login\x18\x01 \x01(\t\x12\r\n\x05likes\x18\x02 \x01(\x05\"A\n\x17GetPopularUsersResponse\x12&\n\x05users\x18\x01 \x03(\x0b\x32\x17.stats_service.UserInfo2\xab\x02\n\x0cStatsService\x12W\n\x0cGetPostStats\x12\".stats_service.GetPostStatsRequest\x1a#.stats_service.GetPostStatsResponse\x12`\n\x0fGetPopularPosts\x12%.stats_service.GetPopularPostsRequest\x1a&.stats_service.GetPopularPostsResponse\x12`\n\x0fGetPopularUsers\x12%.stats_service.GetPopularUsersRequest\x1a&.stats_service.GetPopularUsersResponseB\x04Z\x02./b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\002./'
  _globals['_POSTSTATSBYONEPARAMETER']._serialized_start=30
  _globals['_POSTSTATSBYONEPARAMETER']._serialized_end=102
  _globals['_GETPOSTSTATSREQUEST']._serialized_start=104
  _globals['_GETPOSTSTATSREQUEST']._serialized_end=137
  _globals['_GETPOSTSTATSRESPONSE']._serialized_start=139
  _globals['_GETPOSTSTATSRESPONSE']._serialized_end=191
  _globals['_GETPOPULARPOSTSREQUEST']._serialized_start=193
  _globals['_GETPOPULARPOSTSREQUEST']._serialized_end=252
  _globals['_GETPOPULARPOSTSRESPONSE']._serialized_start=254
  _globals['_GETPOPULARPOSTSRESPONSE']._serialized_end=334
  _globals['_GETPOPULARUSERSREQUEST']._serialized_start=336
  _globals['_GETPOPULARUSERSREQUEST']._serialized_end=375
  _globals['_USERINFO']._serialized_start=377
  _globals['_USERINFO']._serialized_end=417
  _globals['_GETPOPULARUSERSRESPONSE']._serialized_start=419
  _globals['_GETPOPULARUSERSRESPONSE']._serialized_end=484
  _globals['_STATSSERVICE']._serialized_start=487
  _globals['_STATSSERVICE']._serialized_end=786
# @@protoc_insertion_point(module_scope)
