// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: stats.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StatsService_GetPostStats_FullMethodName    = "/stats_service.StatsService/GetPostStats"
	StatsService_GetPopularPosts_FullMethodName = "/stats_service.StatsService/GetPopularPosts"
	StatsService_GetPopularUsers_FullMethodName = "/stats_service.StatsService/GetPopularUsers"
)

// StatsServiceClient is the client API for StatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatsServiceClient interface {
	GetPostStats(ctx context.Context, in *GetPostStatsRequest, opts ...grpc.CallOption) (*GetPostStatsResponse, error)
	GetPopularPosts(ctx context.Context, in *GetPopularPostsRequest, opts ...grpc.CallOption) (*GetPopularPostsResponse, error)
	GetPopularUsers(ctx context.Context, in *GetPopularUsersRequest, opts ...grpc.CallOption) (*GetPopularUsersResponse, error)
}

type statsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsServiceClient(cc grpc.ClientConnInterface) StatsServiceClient {
	return &statsServiceClient{cc}
}

func (c *statsServiceClient) GetPostStats(ctx context.Context, in *GetPostStatsRequest, opts ...grpc.CallOption) (*GetPostStatsResponse, error) {
	out := new(GetPostStatsResponse)
	err := c.cc.Invoke(ctx, StatsService_GetPostStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetPopularPosts(ctx context.Context, in *GetPopularPostsRequest, opts ...grpc.CallOption) (*GetPopularPostsResponse, error) {
	out := new(GetPopularPostsResponse)
	err := c.cc.Invoke(ctx, StatsService_GetPopularPosts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetPopularUsers(ctx context.Context, in *GetPopularUsersRequest, opts ...grpc.CallOption) (*GetPopularUsersResponse, error) {
	out := new(GetPopularUsersResponse)
	err := c.cc.Invoke(ctx, StatsService_GetPopularUsers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServiceServer is the server API for StatsService service.
// All implementations must embed UnimplementedStatsServiceServer
// for forward compatibility
type StatsServiceServer interface {
	GetPostStats(context.Context, *GetPostStatsRequest) (*GetPostStatsResponse, error)
	GetPopularPosts(context.Context, *GetPopularPostsRequest) (*GetPopularPostsResponse, error)
	GetPopularUsers(context.Context, *GetPopularUsersRequest) (*GetPopularUsersResponse, error)
	mustEmbedUnimplementedStatsServiceServer()
}

// UnimplementedStatsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatsServiceServer struct {
}

func (UnimplementedStatsServiceServer) GetPostStats(context.Context, *GetPostStatsRequest) (*GetPostStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostStats not implemented")
}
func (UnimplementedStatsServiceServer) GetPopularPosts(context.Context, *GetPopularPostsRequest) (*GetPopularPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPopularPosts not implemented")
}
func (UnimplementedStatsServiceServer) GetPopularUsers(context.Context, *GetPopularUsersRequest) (*GetPopularUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPopularUsers not implemented")
}
func (UnimplementedStatsServiceServer) mustEmbedUnimplementedStatsServiceServer() {}

// UnsafeStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatsServiceServer will
// result in compilation errors.
type UnsafeStatsServiceServer interface {
	mustEmbedUnimplementedStatsServiceServer()
}

func RegisterStatsServiceServer(s grpc.ServiceRegistrar, srv StatsServiceServer) {
	s.RegisterService(&StatsService_ServiceDesc, srv)
}

func _StatsService_GetPostStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetPostStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetPostStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetPostStats(ctx, req.(*GetPostStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetPopularPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPopularPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetPopularPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetPopularPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetPopularPosts(ctx, req.(*GetPopularPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetPopularUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPopularUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetPopularUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetPopularUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetPopularUsers(ctx, req.(*GetPopularUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatsService_ServiceDesc is the grpc.ServiceDesc for StatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stats_service.StatsService",
	HandlerType: (*StatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPostStats",
			Handler:    _StatsService_GetPostStats_Handler,
		},
		{
			MethodName: "GetPopularPosts",
			Handler:    _StatsService_GetPopularPosts_Handler,
		},
		{
			MethodName: "GetPopularUsers",
			Handler:    _StatsService_GetPopularUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats.proto",
}
